name: pages-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Set up git remote
        run: |
          REMOTE_URL=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git remote set-url origin $REMOTE_URL
          git fetch origin
          git checkout -t origin/gh-pages
          git checkout main
      - name: Set up git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Install dependencies
        run: npm ci
      - name: Synchronize content
        run: npm run sync:content
      - name: Build website
        run: npm run build
      - name: Set up git worktree
        run: |
          git worktree add $RUNNER_TEMP/pages gh-pages
          rm -rf $RUNNER_TEMP/pages/*
          cp -rp public/* $RUNNER_TEMP/pages/
      - name: Check git status
        id: check-git-status
        run: |
          cd $RUNNER_TEMP/pages/
          if [[ `git status --porcelain` ]]; then
            echo '::set-output name=has_changes::true'
          else
            echo 'nothing to publish'
            echo '::set-output name=has_changes::false'
          fi
      - name: Publish website
        if: steps.check-git-status.outputs.has_changes == 'true'
        run: |
          cd $RUNNER_TEMP/pages/
          git add -A && git commit -m 'Publish website'
          git push origin gh-pages
          cd -
